[project]
name = "smallnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.9",
    "matplotlib-inline>=0.2.2",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "tensorly>=0.9.0",
    "tensorly-torch>=0.5.0",
    "thop>=0.1.1.post2209072238",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
    "tqdm>=4.67.3",
]
